## Travis CI Integration

language: csharp
solution: Z80Core/Z80Core.sln

install:
  - nuget restore Z80Core/Z80Core.sln
  - nuget install NUnit.Runners -Version 3.0.1 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Z80Core/Z80Core.sln
  - mono ./testrunner/NUnit.Runners.3.0.1/tools/nunit-console.exe ./Z80Sharp/Z80Core/Z80Core/Z80CoreTests/bin/Release/Z80CoreTests.dll
